version: "3"

services:
  db:
    image: postgres:14
    ports: [ "5432:5432" ]
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python -m gunicorn -b 0.0.0.0:8000 main:app --reload
    volumes:
      - .:/app
    ports: ["8000:8000"]
    depends_on: [db]
    env_file: [".env"]